### ISSUE TITLE
无法运行项目

### ISSUE THREAD

**Issue by shishisana** [dorisoy/Dorisoy.Pan#1]
你好，感谢开源。
我在运行项目的时候发现缺少文件。
1、缺少appsettings文件
2、缺少nlog.config

**Comment by 18338057952** [comment]
无法运行

**Comment by lsl05072239** [comment]
无法运行,缺少数据库

**Comment by dorisoy** [comment]
> 你好，感谢开源。 我在运行项目的时候发现缺少文件。 1、缺少appsettings文件 2、缺少nlog.config
{
    "Logging": {
        "IncludeScopes": false,
        "LogLevel": {
            "Default": "Trace",
            "Microsoft": "Warning",
            "Microsoft.Hosting.Lifetime": "Information",
            "Microsoft.EntityFrameworkCore.Database.Command": "Information"
        },
        "NLog": "你的数据库链接"
    },
    "connectionStrings": {
        "DocumentDbConnectionString": "你的数据库链接"
    },
  "JwtSettings": {
    "key": "xxxx",
    "issuer": "http://localhost:5000",
    "audience": "PTCUsers",
    "minutesToExpiration": "720"
  },
  "UserProfilePath": "Users",
  "WebApplicationUrl": "http://localhost:89,http://localhost:4200",
  "DocumentPath": "Documents",
  "DefaultUserImage": "user-profile.jpg",
  "ExecutableFileTypes": ".bat,.bin,.cmd,.com,.cpl,.exe,.gadget,.inf1,.ins,.inx,.isu,.job,.jse,.lnk,.msc,.msi,.msp,.action,.apk,.app,.command,.csh,.ipa,.ksh,.mst,.osx,.out,.paf,.pif,.run",
  "EncryptionKey": "sfssdsdfsfd",
  "ContentRootPath": ""
}

**Comment by dorisoy** [comment]
> 无法运行,缺少数据库
你好，配置好数据库连接，用 Migrations 还原一下就ok啦~
