### ISSUE TITLE
请问admin@gmail.com、employee@gmail.com的密码是什么？

### ISSUE THREAD

**Issue by dingshixing** [dorisoy/Dorisoy.Pan#11]
不会迁移，数据库里面是密文，不知道加密方式，请问密码是什么呢？现在都跑通了，就是进不去系统

**Comment by dorisoy** [comment]
> 不会迁移，数据库里面是密文，不知道加密方式，请问密码是什么呢？现在都跑通了，就是进不去系统

admin@123
