### ISSUE TITLE
VS2022上运行，无法进行数据库的还原操作，执行Update-Database后会提示：Your startup project 'Dorisoy.Pan.API' doesn't reference Microsoft.EntityFrameworkCore.Design. This package is required for the Entity Framework Core Tools to work. Ensure your startup project is correct, install the package, and try again.

### ISSUE THREAD

**Issue by XiaoYong666** [dorisoy/Dorisoy.Pan#14]
![企业微信截图_1700104548814](https://github.com/dorisoy/Dorisoy.Pan/assets/17639309/bdc97b80-bb3d-4b7d-8317-25ea6e2e5225)

**Comment by dorisoy** [comment]
> ![企业微信截图_1700104548814](https://user-images.githubusercontent.com/17639309/283310507-bdc97b80-bb3d-4b7d-8317-25ea6e2e5225.png)

你需要确认安装：

PM> NuGet\Install-Package Microsoft.EntityFrameworkCore.Design -Version 8.0.0
PM> NuGet\Install-Package Microsoft.EntityFrameworkCore.Tools  -Version 8.0.0

如果在程序包管理器控制台执行脚本，请选择 Dorisoy.Pan.Domain 项目。

PM> Update-Database

或者解决方案：

PM> dotnet ef migrations add InitialCreate --project Dorisoy.Pan.Domain
