### ISSUE TITLE
我的runtime是dotnet 8.0，vs是2022，无法编译以及跑起程序。

### ISSUE THREAD

**Issue by lantianning** [dorisoy/Dorisoy.Pan#15]
<img width="960" alt="屏幕截图" src="https://github.com/dorisoy/Dorisoy.Pan/assets/4702370/ad5c7b11-9b7b-49e4-a023-dfd5931e0489">

**Comment by dorisoy** [comment]
> <img alt="屏幕截图" width="960" src="https://user-images.githubusercontent.com/4702370/285388061-ad5c7b11-9b7b-49e4-a023-dfd5931e0489.png">

已经提示你了啊~~~
The current .NET SDK does not support targeting .NET 8.0. Either target NET 6.0 or lower, or use a version of
the .NET SDK that supports .NET 8.0.

**Comment by dorisoy** [comment]
> <img alt="屏幕截图" width="960" src="https://user-images.githubusercontent.com/4702370/285388061-ad5c7b11-9b7b-49e4-a023-dfd5931e0489.png">

已经提示你了啊~~~
The current .NET SDK does not support targeting .NET 8.0. Either target NET 6.0 or lower, or use a version of
the .NET SDK that supports .NET 8.0.
