### ISSUE TITLE
前端运行和编译都报错

### ISSUE THREAD

**Issue by fsea** [dorisoy/Dorisoy.Pan#17]
PS D:\Download\Dorisoy.Pan-main\UI> npm run start

> dorisoy.pan@1.0.0 start
> SET NODE_OPTIONS=--openssl-legacy-provider && ng serve

✔ Browser application bundle generation complete.

Initial Chunk Files   | Names         |      Size
vendor.js             | vendor        |   2.09 MB
styles.css, styles.js | styles        | 979.73 kB
scripts.js            | scripts       | 814.72 kB
runtime.js            | runtime       |   6.62 kB
main.js               | main          |   5.80 kB

                      | Initial Total |   4.35 MB

Build at: 2023-11-28T02:08:56.622Z - Hash: 210982faa80de4897796 - Time: 4727ms

./src/main.ts:3:0-45 - Error: Module not found: Error: Can't resolve './app/app.module' in 'D:\Download\Dorisoy.Pan-main\UI\src'

Error: src/main.ts:4:27 - error TS2307: Cannot find module './app/app.module' or its corresponding type declarations.

4 import { AppModule } from './app/app.module';
                            ~~~~~~~~~~~~~~~~~~




** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **

终止批处理操作吗(Y/N)? y
PS D:\Download\Dorisoy.Pan-main\UI> npm run build

> dorisoy.pan@1.0.0 build
> SET NODE_OPTIONS=--openssl-legacy-provider && ng build

✔ Browser application bundle generation complete.

./src/main.ts:3:0-45 - Error: Module not found: Error: Can't resolve './app/app.module' in 'D:\Download\Dorisoy.Pan-main\UI\src'

Error: src/main.ts:4:27 - error TS2307: Cannot find module './app/app.module' or its corresponding type declarations.

4 import { AppModule } from './app/app.module';
                            ~~~~~~~~~~~~~~~~~~

PS D:\Download\Dorisoy.Pan-main\UI>

**Comment by dorisoy** [comment]
> PS D:\Download\Dorisoy.Pan-main\UI> npm run start
> 
> > dorisoy.pan@1.0.0 start
> > SET NODE_OPTIONS=--openssl-legacy-provider && ng serve
> 
> ✔ Browser application bundle generation complete.
> 
> Initial Chunk Files | Names | Size vendor.js | vendor | 2.09 MB styles.css, styles.js | styles | 979.73 kB scripts.js | scripts | 814.72 kB runtime.js | runtime | 6.62 kB main.js | main | 5.80 kB
> 
> ```
>                   | Initial Total |   4.35 MB
> ```
> 
> Build at: 2023-11-28T02:08:56.622Z - Hash: 210982faa80de4897796 - Time: 4727ms
> 
> ./src/main.ts:3:0-45 - Error: Module not found: Error: Can't resolve './app/app.module' in 'D:\Download\Dorisoy.Pan-main\UI\src'
> 
> Error: src/main.ts:4:27 - error TS2307: Cannot find module './app/app.module' or its corresponding type declarations.
> 
> 4 import { AppModule } from './app/app.module'; ~~~~~~~~~~~~~~~~~~
> 
> ** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
> 
> 终止批处理操作吗(Y/N)? y PS D:\Download\Dorisoy.Pan-main\UI> npm run build
> 
> > dorisoy.pan@1.0.0 build
> > SET NODE_OPTIONS=--openssl-legacy-provider && ng build
> 
> ✔ Browser application bundle generation complete.
> 
> ./src/main.ts:3:0-45 - Error: Module not found: Error: Can't resolve './app/app.module' in 'D:\Download\Dorisoy.Pan-main\UI\src'
> 
> Error: src/main.ts:4:27 - error TS2307: Cannot find module './app/app.module' or its corresponding type declarations.
> 
> 4 import { AppModule } from './app/app.module'; ~~~~~~~~~~~~~~~~~~
> 
> PS D:\Download\Dorisoy.Pan-main\UI>

## Please compare your node environment，this is my local situation and it works perfectly.  you can refer to it....

 ### node -v  

 v16.15.0

 ### npm version

{
  npm: '8.5.5',
  node: '16.15.0',
  v8: '9.4.146.24-node.20',
  uv: '1.43.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.18.1',
  modules: '93',
  nghttp2: '1.47.0',
  napi: '8',
  llhttp: '6.0.4',
  openssl: '1.1.1n+quic',
  cldr: '40.0',
  icu: '70.1',
  tz: '2021a3',
  unicode: '14.0',
  ngtcp2: '0.1.0-DEV',
  nghttp3: '0.1.0-DEV'
}

 ### ng version

@angular-devkit/architect    0.1502.4
@angular-devkit/core         15.2.4
@angular-devkit/schematics   15.2.4
@schematics/angular          15.2.4

 ### npm view typescript version

5.3.2

------------------------------------------------------
PS D:\Git\Dorisoy.Pan\UI> npm run start
Debugger attached.

> dorisoy.pan@1.0.0 start
> ng serve

Debugger attached.
✔ Browser application bundle generation complete.

Initial Chunk Files                                               | Names         |      Size
vendor.js                                                         | vendor        |   7.96 MB
styles.css, styles.js                                             | styles        | 979.73 kB
main.js                                                           | main          | 823.50 kB
scripts.js                                                        | scripts       | 814.72 kB
polyfills.js                                                      | polyfills     | 510.55 kB
runtime.js                                                        | runtime       |  12.55 kB

                                                                  | Initial Total |  11.02 MB

Lazy Chunk Files                                                  | Names         |      Size
default-node_modules_angular_material_fesm2015_datepicker_js.js   | -             | 322.06 kB
src_app_home_home_module_ts.js                                    | -             | 252.31 kB
default-node_modules_angular_material_fesm2015_table_js.js        | -             | 199.92 kB
src_app_user_user_module_ts.js                                    | -             | 121.54 kB
default-node_modules_angular_material_fesm2015_input_js.js        | -             |  62.86 kB
src_app_n-log_n-log_module_ts.js                                  | -             |  61.56 kB
src_app_email-smtp-setting_email-smtp-setting_module_ts.js        | -             |  54.56 kB
src_app_shared-file_shared-file_module_ts.js                      | -             |  48.24 kB
default-node_modules_angular_material_fesm2015_sort_js.js         | -             |  47.93 kB
src_app_email-send_email-send_module_ts.js                        | -             |  46.55 kB
src_app_starred-file_starred-file_module_ts.js                    | -             |  45.64 kB
src_app_email-template_email-template_module_ts.js                | -             |  43.35 kB
src_app_notification_notification_module_ts.js                    | -             |  42.38 kB
src_app_recent-activity_recent-activity_module_ts.js              | -             |  39.71 kB
default-node_modules_angular_material_fesm2015_slide-toggle_js.js | -             |  39.11 kB
src_app_dashboard_dashboard_module_ts.js                          | -             |  38.81 kB
src_app_deleted-file_deleted-file_module_ts.js                    | -             |  36.40 kB
src_app_login-audit_login-audit_module_ts.js                      | -             |  36.22 kB
src_app_login_login_module_ts.js                                  | -             |  31.71 kB
common.js                                                         | common        |   3.24 kB

Build at: 2023-11-29T03:16:10.091Z - Hash: 96222c6c412ee026b7c0 - Time: 29829ms

** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **


√ Compiled successfully.

**Comment by fsea** [comment]
PS D:\Download\Dorisoy.Pan-main\UI> node -v
v18.13.0
PS D:\Download\Dorisoy.Pan-main\UI> npm version
{
  npm: '8.19.3',
  node: '18.13.0',
  v8: '10.2.154.23-node.21',
  uv: '1.44.2',
  zlib: '1.2.13',
  brotli: '1.0.9',
  ares: '1.18.1',
  modules: '108',
  nghttp2: '1.51.0',
  napi: '8',
  llhttp: '6.0.10',
  uvwasi: '0.0.13',
  openssl: '3.0.7+quic',
  cldr: '42.0',
  icu: '72.1',
  tz: '2022f',
  unicode: '15.0',
  ngtcp2: '0.8.1',
  nghttp3: '0.7.0'
}
PS D:\Download\Dorisoy.Pan-main\UI> ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Node: 18.13.0 (Unsupported)
OS: win32 x64

Angular: 12.2.7
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, material, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1202.7
@angular-devkit/build-angular   12.2.7
@angular-devkit/core            10.2.3
@angular-devkit/schematics      10.2.3
@schematics/angular             9.1.15
rxjs                            6.6.7
typescript                      4.3.5

Warning: The current version of Node (18.13.0) is not supported by Angular.
PS D:\Download\Dorisoy.Pan-main\UI> npm view typescript version
5.3.2
PS D:\Download\Dorisoy.Pan-main\UI> npm run start

> dorisoy.pan@1.0.0 start
> SET NODE_OPTIONS=--openssl-legacy-provider && ng serve

✔ Browser application bundle generation complete.

Initial Chunk Files   | Names         |      Size
vendor.js             | vendor        |   2.09 MB
styles.css, styles.js | styles        | 979.73 kB
scripts.js            | scripts       | 814.72 kB
polyfills.js          | polyfills     | 510.55 kB
runtime.js            | runtime       |   6.62 kB
main.js               | main          |   5.80 kB

                      | Initial Total |   4.35 MB

Build at: 2023-11-29T03:41:41.154Z - Hash: 210982faa80de4897796 - Time: 4490ms

./src/main.ts:3:0-45 - Error: Module not found: Error: Can't resolve './app/app.module' in 'D:\Download\Dorisoy.Pan-main\UI\src'

Error: src/main.ts:4:27 - error TS2307: Cannot find module './app/app.module' or its corresponding type declarations.

4 import { AppModule } from './app/app.module';
                            ~~~~~~~~~~~~~~~~~~




** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **

终止批处理操作吗(Y/N)? y
PS D:\Download\Dorisoy.Pan-main\UI>
