### ISSUE TITLE
演示环境的账号密码是更换了嘛

### ISSUE THREAD

**Issue by Rabbit-hub** [dorisoy/Dorisoy.Pan#22]

**Comment by Rabbit-hub** [comment]
本地运行后端代码出现：System.MissingMethodException: Method not found: 'Void CoreTypeMappingParameters..ctor(System.Type, Microsoft.EntityFrameworkCore.Storage.ValueConversion.ValueConverter, Microsoft.EntityFrameworkCore.ChangeTracking.ValueComparer, 
不知道是什么原因

**Comment by dorisoy** [comment]
The demo password is : dorisoy123456
