### ISSUE TITLE
登录UI和截屏的不一样，上传文件失败

### ISSUE THREAD

**Issue by sunzq071** [dorisoy/Dorisoy.Pan#24]
这是上传文件失败
![error](https://github.com/dorisoy/Dorisoy.Pan/assets/35132187/f55c534b-d890-4077-81a9-e6997537c275)

这是登录界面
![error7](https://github.com/dorisoy/Dorisoy.Pan/assets/35132187/09710d74-23c0-4580-8eeb-db622b9c8137)

**Comment by zzti** [comment]
@sunzq071 你这个问题搞好了没有呢，我的也是这个错误
