### ISSUE TITLE
Unable to create a 'DbContext' of type ''. The exception 'Unable to resolve service for type 'Microsoft.EntityFrameworkCore.DbContextOptions'

### ISSUE THREAD

**Issue by Mr-SunJun** [dorisoy/Dorisoy.Pan#30]
![11](https://github.com/dorisoy/Dorisoy.Pan/assets/74604156/b31ba18b-b5e4-4001-a3ea-5366853ba7e1)

尝试了这个命令 , 但是无法初始化sql脚本,请问你的数据库连接配置是不是这样配置的呢
Update-Database

![企业微信截图_17138446918650](https://github.com/dorisoy/Dorisoy.Pan/assets/74604156/9e272660-4552-4968-9b3a-a04571be9be3)

如下命令我也尝试了,但是还是无法启动命令

你需要确认安装：

PM> NuGet\Install-Package Microsoft.EntityFrameworkCore.Design -Version 8.0.0
PM> NuGet\Install-Package Microsoft.EntityFrameworkCore.Tools -Version 8.0.0

如果在程序包管理器控制台执行脚本，请选择 Dorisoy.Pan.Domain 项目。

PM> Update-Database
PM> dotnet ef migrations add InitialCreate --project Dorisoy.Pan.Domain

是不是因为我数据库连接配置出错导致的呢

**Comment by wdjlover** [comment]
需要先将Dorisoy.Pan.API 设为启动项目，然后在pm中选择Dorisoy.Pan.Domain为默认项目。然后在pm控制台执行Update-Database。另外如果使用mysql，注意版本。
