### ISSUE TITLE
无法上传，桌面端干脆编译不过去

### ISSUE THREAD

**Issue by samtown** [dorisoy/Dorisoy.Pan#32]
![image](https://github.com/dorisoy/Dorisoy.Pan/assets/17312383/6391e71e-51a0-43c5-ac9b-e77d763d7069)
![image](https://github.com/dorisoy/Dorisoy.Pan/assets/17312383/30ccba88-1699-47e9-a605-ec971126965d)

**Comment by cejpo001** [comment]
请问你解决了吗？我也遇到这个问题
