### ISSUE TITLE
UI里没有package.json文件能否提供？

### ISSUE THREAD

**Issue by stephenccz** [dorisoy/Dorisoy.Pan#4]
前端页面好像没有？而且UI里没有package.json文件

**Comment by dorisoy** [comment]
> 前端页面好像没有？而且UI里没有package.json文件

你好！appsettings可以自行还原下，或者参考 https://github.com/dorisoy/Dorisoy.Pan/issues/1

**Comment by stephenccz** [comment]
后台API是运行起来了，但UI文件夹用VSCODE运行不起来，没有package.json文件，npm安装不上。

**Comment by dorisoy** [comment]
github 加个 follow，微信我 dorisoy88，给你指导下



在 2023-02-12 16:51:02，"stephenccz" ***@***.***> 写道：

后台API是运行起来了，但UI文件夹用VSCODE运行不起来，没有package.json文件，npm安装不上。
